name: ITI Lab CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deliver:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: build docker image and push to hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
          image: compilereg/itioswebapp
          registry: docker.io
          dockerfile: Dockerfile
          username: "${{ secrets.HUB_USERNAME }}"
          password: "${{ secrets.HUB_PASSWORD }}"
          tags: latest  
