name: ITI Lab CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build_and_push_to_dockerhub: 
  runs-on: ubuntu-latest
  steps:
      - name: checkout repo 
        uses: actions/checkout@v3
      
      - name: set up docker build
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # use username/repositoryName:anyTag format
          tags: omarfouad/appNodejs:1.0
          cache-from: type=registry,ref=omarfouad/appNodejs:1.0
          cache-to: type=inline
                  
                
